<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Carbon\Carbon;
use DB;

class AdsRevenueCalc extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'bbg:ads-revenue-calc';

    /**
     * The console command description.
     *
     * @var string
     */

    protected $description = 'Calculate revenue generated by all adverts';

    /**
     * Execute the console command.
     */

    public function handle()
    {
        $ads = DB::table('adverts') -> where('status', 'active') -> get();
        $partners = DB::table('rhythmbox') -> get(); 

        foreach ($ads as $key => $ad) {
            $current_date = Carbon::parse(date('Y-m-d H:m:s'));
            $ad_posted_on = Carbon::parse($ad -> posted_on);

            $ad_yeas_taken = $current_date -> diffInYears($ad_posted_on);
            $ad_months_taken = $current_date -> diffInMonths($ad_posted_on);
            $ad_days_taken = $current_date -> diffInDays($ad_posted_on);
            
            if($ad -> payment_circle == 'daily') {
                $amount_gen = $ad -> amount * $ad_days_taken;
                DB::table('adverts') -> where('id', $ad -> id) -> limit(1) -> update(['amount_gen' => $amount_gen]);

                foreach ($partners as $partner) {
                        
                    $percentage = $partner -> pending_amount + (($amount_gen * $partner -> revenues_percentage) / 100);
        
                    DB::table('rhythmbox') -> limit(1) -> where('id', $partner -> id) -> update(['pending_amount' => $percentage]);
        
                }
            }
        }
    }
}
